### ISSUE TITLE
Add swagger doc for REST API

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#12]
Required actions:
1. Create Swagger doc
1. Create endpoint to host swagger doc

**Comment by shreyaa-sharmaa** [comment]
I'm interested to work on this.

**Comment by ashokponkumar** [comment]
@swati-nair Do let us know if you need more information on this.

**Comment by swati-nair** [comment]
Sure @ashokponkumar, thank you!
I have started working on it and I am using go-swagger to generate the swagger doc.

**Comment by HarikrishnanBalagopal** [comment]
Useful links:
- https://swagger.io/docs/specification/2-0/what-is-swagger/
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md
- https://github.com/go-swagger/go-swagger
- https://medium.com/@pedram.esmaeeli/generate-swagger-specification-from-go-source-code-648615f7b9d9
