### ISSUE TITLE
Improve Go Report score to A+

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#18]
Fix Go lint issues listed in https://goreportcard.com/report/github.com/konveyor/move2kube-api

**Comment by burnerlee** [comment]
@ashokponkumar can i please work on this issue. I'll make a PR by tomorrow

**Comment by ashokponkumar** [comment]
> @ashokponkumar can i please work on this issue. I'll make a PR by tomorrow

sure @burnerlee. Looking forward to reviewing your pull request.

**Comment by ashokponkumar** [comment]
Fixed by #22 #23 #24
