### ISSUE TITLE
Clean up logs

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#25]
1. For each function check if the current logs are correct.
1. Check if any error is being ignored it is logged if necessary.
1. Add debug logs where it might help in functions when starting any action/function.
1. Print informative logs whenever a new request comes and success/error messages.

**Comment by PankhudiB** [comment]
I can help on this one

**Comment by ashokponkumar** [comment]
Sure @PankhudiB . Please reach out if you have any specific questions

**Comment by ashokponkumar** [comment]
@Akash-Nayak Also would be good to have debug mode which can be triggered from the url. So that from the UI, say if we put ?debug=true, it invokes the debug mode for Move2Kube and the in code logs in general.

**Comment by Akash-Nayak** [comment]
> @Akash-Nayak Also would be good to have debug mode which can be triggered from the url. So that from the UI, say if we put ?debug=true, it invokes the debug mode for Move2Kube and the in code logs in general.

Yes sure.
