### ISSUE TITLE
Use regex substring to get portion of string

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#27]
https://github.com/konveyor/move2kube-api/blob/3d77a865c2a573bef550f412fab3487afc17f72f/main.go#L185-L192

Change above code to not look for specific strings. Rather just do a substring on the regex extracted string or create a bracketed regex, and identify the match and use that as artifactname

**Comment by isabellaliu77** [comment]
Hi, can I work on this one? Thanks.

**Comment by ashokponkumar** [comment]
> Hi, can I work on this one? Thanks.

Sure @isabellaliu77 . Have assigned the issue to you.

**Comment by isabellaliu77** [comment]
Thank you! For this issue, do you mean that you want a bracketed regex instead of strings like "helm" or "knative"?

**Comment by ashokponkumar** [comment]
We want to remove the hardcoding of the 3 artifact types, since move2kube can keep changing and this can get disconnected.

One way to achive it is using regex groups.
 https://stackoverflow.com/questions/30483652/how-to-get-capturing-group-functionality-in-go-regular-expressions

Another way is to use substring after marching the entire artifact type line.

**Comment by isabellaliu77** [comment]
Hey, sorry for the delay, I made a PR for this issue, please check if it satisfies, and let me know if any modification is needed.

**Comment by ashokponkumar** [comment]
Thanks for the fix. Have suggested some changes please have a look.
