### ISSUE TITLE
Irrespective of the target artifact type selected, the artifact type name seem to have "yaml"

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#31]
Describe the bug
During translate choose "helm" as artifact time, the artifact filename should be helm now. But it shows up as yaml.

To Reproduce
During translate choose "helm" as artifact time, the artifact filename should be helm now. But it shows up as yaml.

**Comment by Akash-Nayak** [comment]
Removed artifacttype name "Yamls" which was getting picked-up from plan file. https://github.com/konveyor/move2kube-api/pull/43
