### ISSUE TITLE
When relaying logs from move2kube cli, the logging level (warn, info, debug..) should be maintained

### ISSUE THREAD

**Issue by ashokponkumar** [konveyor/move2kube-api#57]
**Describe the bug**
Currently move2kube just prints all logs from the cli as info logs

**To Reproduce**
1. Run move2kube-aio image
2. Start a plan creation
3. All messages from move2kube gets displayed as info message.

**Expected behavior**
The logging level from move2kube should be maintained by move2kube-api too

**Comment by Akash-Nayak** [comment]
I am closing this issue as discussed today.
